
NAME=ft_advanced_do-op
SRCS=srcs/do_op.c srcs/ft_atoi.c srcs/ft_add.c srcs/ft_div.c srcs/ft_mod.c srcs/ft_mul.c srcs/ft_sub.c srcs/ft_usage.c

all:
	gcc $(SRCS) -o $(NAME)

clean:
	/bin/rm -f $(NAME)

re: clean all
